Update some tools

diff --git a/bin/executable_take b/bin/executable_take
--- a/bin/executable_take
+++ b/bin/executable_take
@@ -1,144 +1,112 @@
-#!/usr/bin/ruby
+#!/usr/bin/env zsh
+# A bag to carry files around as you go from directory to directory
+#
+# This should be linked to the following names: inv, take, drop
 
-require 'fileutils'
-require 'optparse'
-require 'pp'
-require 'shellwords'
+##############################################################################
+argv0=${${0:t}:r}
 
-name = File.basename($0)
-# TODO: Allow EVN override
-inv_space = File.join(Dir.home(), ".local", "state", "inv", "files")
-inv_bd = File.dirname(inv_space)
+# Check that argv0 is one of the expected commands
+if [[ "$argv0" != "inv" && "$argv0" != "take" && "$argv0" != "drop" ]]; then
+  echo "Usage: $argv0 [options] <args>" >&2
+  echo "Available commands: inv, take, drop" >&2
+  exit 1
+fi
 
-if name == "take" then
-  options = {}
-  OptionParser.new do |opts|
-    opts.banner = "Usage: take [options] file…"
+# Separate options and arguments out of the cmdline
+typeset -A Options
+Args=()
+for opt in "$@"; do
+  case $opt in
+    --h|--help) Options[help]=1 ;;
+    --append|-a|--add) Options[add]=1 ;;
+    --move|-m) Options[move]=1 ;;
+    --select|-s) Options[select]=1 ;;
+    --verbose|-v) Options[verbose]=1 ;;
+    *) Args+=("$opt") ;;
+  esac
+done
 
-    opts.on("-c", "--copy", "Copy file paths to system clipboard") do |v|
-      options[:copy] = v
-    end
-    opts.on("-a", "--add", "Add files to inv instead of replacing") do |v|
-      options[:add] = v
-    end
-    opts.on("-h", "--help", "Prints this help") do
-      puts opts
-      exit
-    end
-  end.parse!
+##############################################################################
+# Some helpers
+function _get_bag {
+  local bag=".local/state/inv/files"
+  mkdir -p ${bag:h}
+  echo $bag
+}
 
-  pwd = Dir.getwd
-  files = ARGV.map{|f| File.join(pwd, f) }.shelljoin
-  if options[:copy] then
-    IO.popen("pbcopy", 'w') { |io| io << files }
+##############################################################################
+
+# Since we have three top level commands that don't have sub commands, we implement them
+# all as the 'task not found' handler. This is a bit of a hack, but it works.
+function inv_help {
+  echo "inv - show the contents of the bag"
+}
+function inv {
+  local bag=$(_get_bag)
+  [[ -f "$bag" ]] && cat $bag
+}
+
+function take_help {
+  echo "take - add files or directories to the bag"
+  echo "Usage: take [options] <file1> <file2> ..."
+  echo "Options:"
+  echo "  --append, -a    Append to the existing bag instead of replacing it"
+  echo "  --add           Same as --append"
+} 
+function take {
+  # Write to the bag file, each arg on one line.
+  # Replacing old bag unless --append or --add is given
+  local bag=$(_get_bag)
+  if [[ -z "${Options[add]}" ]]; then
+    rm -f $bag
+  fi
+  for arg in $*; do
+    # Get the absolute path
+    [[ -e "$arg" ]] && realpath "$arg" >> $bag
+  done
+}
+
+function drop_help {
+  echo "drop - copy or move files from the bag to the current directory or a specified directory"
+  echo "Usage: drop [options] [destination]"
+  echo "Options:"
+  echo "  --move, -m      Move files instead of copying them"
+  echo "  --select, -s    Use fzf to select files to drop"
+  echo "If no destination is given, the current directory is used"
+}
+function drop {
+  local dest=${1:-$PWD}
+  [[ ! -d "$dest" ]] && echo "Error: $dest is not a directory" >&2 && return
+  local bag=$(_get_bag)
+  [[ ! -f "$bag" ]] && return
+  local to_drop
+  # if --select is given, use the fzf to select files to drop
+  if [[ -n "${Options[select]}" ]]; then
+    cat $bag | fzf -m --prompt="Select files to drop> " | IFS=$'\n' read -d '' -r -A to_drop
+    if [[ ${#to_drop[@]} -eq 0 ]]; then
+      echo "No files selected to drop"
+      return
+    fi
   else
-    FileUtils.makedirs(inv_bd) unless Dir.exist?(inv_bd)
-    if options[:add] then
-      old = if File.exist?(inv_space) then
-               File.open(inv_space, 'r') {|io| io.read }
-             else
-               ""
-             end.shellsplit
-      files.prepend(*old)
-    end
-    File.open(inv_space, 'w') { |io| io << files }
-  end
-
-
-elsif name == "drop" then
-  options = {}
-  OptionParser.new do |opts|
-    opts.banner = "Usage: drop [options] [dest]"
-
-    opts.on("-p", "--paste", "Use file paths from system clipboard") do |v|
-      options[:paste] = v
-    end
-    opts.on("-m", "--move", "Move files instead of copying them") do |v|
-      options[:move] = v
-    end
-    opts.on("-s", "--select [pattern]", Regexp, "Only drop files matching pattern") do |v|
-      options[:select] = v
-    end
-    opts.on("-h", "--help", "Prints this help") do
-      puts opts
-      exit
-    end
-  end.parse!
-
-  files = if options[:paste] then
-            `pbpaste`
-           else
-             if File.exist?(inv_space) then
-               File.open(inv_space, 'r') {|io| io.read }
-             else
-               ""
-             end
-           end.shellsplit
-
-  remaining = []
-  if options[:select] then
-    remaining = files.reject { |e| options[:select].match(e) }
-    files.select! { |e| options[:select].match(e) }
-  end
-
-  dest = if ARGV[0].nil?
-           Dir.getwd
-         else
-           if File.directory?(ARGV[0]) then
-             ARGV[0]
-           else
-             File.dirname(ARGV[0])
-           end
-         end
-  if options[:move] then
-    FileUtils.mv(files, dest)
-  else
-    FileUtils.cp_r(files, dest)
-  end
-
-  # only remove items actually dropped.
-  unless options[:paste] then
-    if options[:select] and not remaining.empty? then
-      FileUtils.makedirs(inv_bd) unless Dir.exist?(inv_bd)
-      File.open(inv_space, 'w') { |io| io << remaining.shelljoin }
+    IFS=$'\n' read -d '' -r -A to_drop < $bag
+  fi
+  # if --move, move to the given directory otherwise copy
+  # don't update the bag until after all files are copied/moved
+  for file in $to_drop; do
+    if [[ ! -e "$file" ]]; then
+      [[ -n "$Options[verbose]" ]] && echo "Warning: $file does not exist, skipping"
+      continue
+    fi
+    if [[ -n "$Options[move]" ]]; then
+      mv "$file" "$dest"
     else
-      File.delete(inv_space)
-    end
-  end
+      cp -r "$file" "$dest"
+    fi
+  done
+}
 
-elsif name == "inv" then
-  options = {}
-  OptionParser.new do |opts|
-    opts.banner = "Usage: inv [options]"
+##############################################################################
 
-    opts.on("-p", "--peek", "Use file paths from system clipboard") do |v|
-      options[:paste] = v
-    end
-    opts.on("-s", "--select [pattern]", Regexp, "Only show files matching pattern") do |v|
-      options[:select] = v
-    end
-    opts.on("-h", "--help", "Prints this help") do
-      puts opts
-      exit
-    end
-  end.parse!
-
-  files = if options[:paste] then
-            `pbpaste`
-           else
-             if File.exist?(inv_space) then
-               File.open(inv_space, 'r') {|io| io.read }
-             else
-               ""
-             end
-           end.shellsplit
-
-  if options[:select] then
-    files.select! { |e| options[:select].match(e) }
-  end
-
-  # Pretty up the output.
-  pp files
-end
-
-#  vim: set sw=2 ts=2 et :
+[[ -n "${Options[help]}" ]] && "${argv0}_help" && exit 0
+${argv0} "${Args[@]}"
